### ISSUE TITLE
Add dry run option for PR validation

### ISSUE THREAD

**Issue by jpower432** [RedHatProductSecurity/trestle-bot#181]
**Is your feature request related to a problem? Please describe.**

The `check only` option exists to error when information is out of sync. A dry run option as a simple validation that assemble is completed successful without changing the branch would be useful for change validation during the PR process.

**Describe the solution you'd like**

Remove the `check_only` flag and add a dry run option.
There should be a way for a user to understand if there were changes or not through output and logged messages. Then the user could determine whether to fail for changes or not.

**Acceptance Criteria**
- [x] Remove check_only flag
- [x] Add a more precise flag for dry run. Possibly (`push=false`)
- [x] Add a logged message with dry run to show what would have been updated.
- [ ] Stretch Goal: *Should be documented in another issue* - Comment on the PR if triggered through that process

**Describe alternatives you've considered**
The `TrestleBot` class has a dry-run option. This could simply be exposed, but that could be confusing when here is already a `check_only` flag and the option does not have output that would be helpful to a user.

**Additional context**
This will be a breaking change so that release notes should have upgrade information. Documentation will need to updated to show how to fail a pipeline when changed are found and that is unexpected.

**Comment by jpower432** [comment]
@beatrizmcouto Currently testing some work around this feature and suggest we move the commenting feature to a new issue since it is slightly more complex. WDYT?

**Comment by beatrizmcouto** [comment]
Let's discuss in the daily later today
