### ISSUE TITLE
Website creation

### ISSUE THREAD

**Issue by beatrizmcouto** [RedHatProductSecurity/trestle-bot#305]
- [x] add training content

**Comment by beatrizmcouto** [comment]
Linking website here - still WIP: https://redhatproductsecurity.github.io/trestle-bot/

**Comment by gvauter** [comment]
Added issue https://github.com/RedHatProductSecurity/trestle-bot/issues/338 to fix CI for website.

**Comment by huiwangredhat** [comment]
Pls ignore this message. This is testing for sync2jira to catch the logs
